### ISSUE TITLE
unable to get ssm automation job status details in cloudmigration factory console

### ISSUE THREAD

**Issue by Dips2803** [aws-solutions/cloud-migration-factory-on-aws#26]
HI Team,

I initiated a job with SSM automation execution in the cloud migration factory console via automation server instance.

The jobs completed in SSM however, the status couldnt be updated back in the cloud migration factory. Typically the jobs are showing timed out in the factory console. Checked dynamo db table and it shows timed out as well. But the SSM automation document run completed successfully. We need to know why job status is not updating in cloud migration factory. We used migration factory public type deployment.

Let me know if some screenshots/logs required. 

Regards
Dips

**Comment by chris-p-baker** [comment]
Hi @Dips2803, sorry for the delay please could you send a screenshot to the email address migration-factory-support@amazon.com and we will take a look.
