### ISSUE TITLE
Deployment error with bucket policy using OAI

### ISSUE THREAD

**Issue by Kobayashi-Riku0226** [aws-solutions/cloud-migration-factory-on-aws#27]
https://github.com/aws-solutions/cloud-migration-factory-on-aws/blob/master/deployment/CFN-templates/aws-cloud-migration-factory-solution.template

When deploying an AWS resource using the above template, the following error occurs in "FrontEndBucketPolicy".
```
cloudfront oai resource handler returned message: "invalid principal in policy
```

So please change to a template that uses OAC.

**Comment by chris-p-baker** [comment]
Thanks @Kobayashi-Riku0226 this update is now included within v3.3.1 release due today (23rd October 2023).
