### ISSUE TITLE
Missing Import for `base64` standard library

### ISSUE THREAD

**Issue by seantibor** [aws-solutions/cloud-migration-factory-on-aws#35]
The import for the `base64` library is missing in this file. This is causing an error and preventing CMF lambdas from executing properly.

https://github.com/aws-solutions/cloud-migration-factory-on-aws/blob/a36e1ef46ddac3d824337dcac12a1b69f6175cb2/source/backend/lambda_layers/lambda_layer_policy/python/policy.py#L232

We are seeing this error in cloudwatch when trying to update the account list attribute in the Applications administration area.

`[ERROR]	2024-05-07T22:33:18.809Z	a4dcda80-da0a-43ab-83d1-b388c7f9d328	Denying Admin API Access, Claims Error, name 'base64' is not defined`

**Comment by abewub** [comment]
Thanks for reporting that. We will include the fix in the next release.

**Comment by chris-p-baker** [comment]
This issue is resolved in v3.3.5 due to release 8 August 2024.
