### ISSUE TITLE
MGNAPIDeploy fails to deploy

### ISSUE THREAD

**Issue by sleepwithcoffee** [aws-solutions/cloud-migration-factory-on-aws#39]
**Describe the bug**
Cannot deploy the CFN stack due to MGNAPIDeploy failed to deploy.

**To Reproduce**
Download v3.3.5 CloudFormation template and deploy with these parameters:
* DeploymentType: Private
* CognitoFederation: false
* Tracker: true
* ReplatformEC2: true
* Others left with sensible values

**Expected behavior**

**Please complete the following information about the solution:**
- [x] Version: v3.3.5

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0097) - AWS CloudEndure Migration Factory Solution. Version **v1.1.0**_".

- [x] Region: ap-southeast-1
- [x] Was the solution modified from the version published on this repository? NO
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? - YES, and this is a brand new account
- [x] Were there any errors in the CloudWatch Logs? - No

**Screenshots**
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/becf1142-afd4-4468-9b51-3ecab2d13d65">

**Additional context**

**Comment by sleepwithcoffee** [comment]
I tried to diagnose the problem and figured out that the `AppMigService` might need to have some resources of ToolsAPI to be ready, adding the following DependsOn will help:

```
AppMigService:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - ToolsAPIDeploy
 ```

I plan to create a PR to accommodate this fix.

**Comment by chris-p-baker** [comment]
Hi @sleepwithcoffee, thanks for raising this issue, the PR you have provided will be pulled ASAP.

**Comment by chris-p-baker** [comment]
As of v4.0.0 your update has been included. Thanks again for the contribution.
